// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations.ItemDb
{
    [DbContext(typeof(ItemDbContext))]
    partial class ItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Data.Item", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<string>("Specs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidityDate")
                        .HasColumnType("date");

                    b.HasKey("ProductCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BlazorApp1.Data.Record", b =>
                {
                    b.Property<string>("OperationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("date");

                    b.Property<string>("OperationItemProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OperationName")
                        .HasColumnType("int");

                    b.Property<int>("OperationNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperationCode");

                    b.HasIndex("OperationItemProductCode");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("BlazorApp1.Data.Record", b =>
                {
                    b.HasOne("BlazorApp1.Data.Item", "OperationItem")
                        .WithMany("Records")
                        .HasForeignKey("OperationItemProductCode");

                    b.Navigation("OperationItem");
                });

            modelBuilder.Entity("BlazorApp1.Data.Item", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
